import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { initProject } from '../src/project.js';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const cli = fileURLToPath(new URL('../src/cli.js', import.meta.url));
test('CLI delegates native generation as arguments and rejects an App-owned tool', { skip: process.platform === 'win32' }, async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'nexia-generator-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const bin = path.join(root, 'bin');
  const directory = path.join(root, 'app with spaces');
  await mkdir(bin);
  await mkdir(directory);
  const log = path.join(root, 'arguments.json');
  await writeFile(path.join(bin, 'php'), `#!${process.execPath}\nimport('node:fs').then(fs => fs.writeFileSync(process.env.GENERATOR_LOG, JSON.stringify(process.argv.slice(2))));\n`, { mode: 0o755 });
  await writeFile(path.join(bin, 'nexia-app'), '<?php // test tool', { mode: 0o755 });
  const invoke = (args, toolPath = bin) => new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cli, ...args], { env: { ...process.env, PATH: `${toolPath}${path.delimiter}${bin}`, GENERATOR_LOG: log, NEXIA_CONFIG_HOME: path.join(root, 'config') }, stdio: ['ignore', 'pipe', 'pipe'] });
    let output = '';
    child.stdout.on('data', chunk => { output += chunk; });
    child.stderr.on('data', chunk => { output += chunk; });
    child.once('error', reject);
    child.once('close', code => resolve({ code, output }));
  });
  let result = await invoke(['init', directory, '--vendor', 'acme', '--family', 'people', '--name', 'LeaveManager', '--dry-run']);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')), [await realpath(path.join(bin, 'nexia-app')), 'make:app', 'LeaveManager', '--directory', directory, '--vendor', 'acme', '--family', 'people', '--dry-run', '--no-interaction']);
  // Creating source must not contact an old platform session or implicitly link it.
  await mkdir(path.join(root, 'config'));
  const expired = JSON.stringify({ endpoint: 'http://localhost:1', token: 'expired-fixture-token' });
  await writeFile(path.join(root, 'config', 'connection.json'), expired);
  result = await invoke(['init', directory, '--vendor', 'acme', '--family', 'people', '--name', 'LeaveManager']);
  assert.equal(result.code, 1, result.output);
  assert.match(result.output, /Existing files were not changed/);
  assert.equal(await readFile(path.join(root, 'config', 'connection.json'), 'utf8'), expired);
  await assert.rejects(readFile(path.join(directory, '.nexia', 'project.json')), { code: 'ENOENT' });
  result = await invoke(['make:resource', 'Request', directory, '--label-ko', '휴가 신청']);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['make:resource', directory, 'Request', '--label-ko', '휴가 신청', '--no-interaction']);
  result = await invoke(['make:resource', 'Request', directory, '--label-ko', '휴가 신청', '--with-filament']);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['make:resource', directory, 'Request', '--label-ko', '휴가 신청', '--with-filament', '--no-interaction']);
  result = await invoke(['make:page', 'LeaveCalendar', directory, '--label-ko', '휴가 달력', '--without-record', '--without-navigation', '--dry-run']);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['make:page', directory, 'LeaveCalendar', '--label-ko', '휴가 달력', '--without-record', '--without-navigation', '--dry-run', '--no-interaction']);
  const sourceOptions = ['--subject-resource-key', 'leave.request', '--source-resource-key', 'leave.request', '--cardinality', 'many', '--min-items', '0', '--max-items', '12'];
  for (const writeOptions of [[], ['--write'], ['--write', '--force']]) {
    result = await invoke(['make:signature-data-source', 'SelectedRequests', directory, ...sourceOptions, ...writeOptions]);
    assert.equal(result.code, 0, result.output);
    assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['make:signature-data-source', directory, 'SelectedRequests', ...sourceOptions, ...writeOptions, '--no-interaction']);
  }
  const lastInvocation = await readFile(log, 'utf8');
  result = await invoke(['make:signature-data-source', 'SelectedRequests', directory, '--without-navigation']);
  assert.equal(result.code, 1);
  assert.equal(await readFile(log, 'utf8'), lastInvocation);
  await writeFile(path.join(directory, 'composer.json'), '{}');
  result = await invoke(['validate', directory]);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['validate', directory, '--no-interaction']);
  await writeFile(path.join(directory, 'nexia.json'), JSON.stringify({ schema_version: '2', runtime: 'laravel', app: { app_key: 'native-proof' } }));
  result = await invoke(['validate', directory]);
  assert.equal(result.code, 0, 'Native validation must not require preview screens or public/index.html');
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['validate', directory, '--no-interaction']);
  await writeFile(path.join(bin, 'php'), `#!${process.execPath}\nprocess.exit(1);\n`, { mode: 0o755 });
  result = await invoke(['validate', directory]);
  assert.equal(result.code, 1, 'Native validation must preserve PHP validator failures');
  await writeFile(path.join(bin, 'php'), `#!${process.execPath}\nimport('node:fs').then(fs => fs.writeFileSync(process.env.GENERATOR_LOG, JSON.stringify(process.argv.slice(2))));\n`, { mode: 0o755 });
  const hybrid = path.join(root, 'hybrid');
  await initProject(hybrid);
  await writeFile(path.join(hybrid, 'composer.json'), '{}');
  result = await invoke(['validate', hybrid]);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).slice(1), ['validate', hybrid, '--no-interaction']);
  await rm(path.join(hybrid, 'public/index.html'));
  result = await invoke(['validate', hybrid]);
  assert.equal(result.code, 1, 'PHP validation must not skip broken browser entries');
  await writeFile(path.join(directory, 'nexia-app'), '<?php throw new Exception("must not run");', { mode: 0o755 });
  result = await invoke(['make:resource', 'Request', directory], directory);
  assert.equal(result.code, 1);
  assert.match(result.output, /independently installed/);
  result = await invoke(['init', directory]);
  assert.equal(result.code, 1);
  assert.match(result.output, /require --vendor/);
});

test('managed generators install through nexia without global Composer or App scripts', { skip: process.platform === 'win32' }, async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'nexia-managed-generator-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const bin = path.join(root, 'bin');
  const config = path.join(root, 'config');
  const log = path.join(root, 'install.json');
  await mkdir(bin);
  await writeFile(path.join(bin, 'php'), `#!${process.execPath}\nprocess.exit(0);\n`, { mode: 0o755 });
  await writeFile(path.join(bin, 'composer'), `#!${process.execPath}
const fs = require('node:fs');
fs.writeFileSync(process.env.INSTALL_LOG, JSON.stringify({ args: process.argv.slice(2), cwd: process.cwd(), home: process.env.COMPOSER_HOME }));
fs.mkdirSync('vendor/bin', { recursive: true });
fs.writeFileSync('vendor/bin/nexia-app', '<?php // installed generator');
fs.writeFileSync('composer.lock', JSON.stringify({ packages: [{ name: 'nexia-cloud-os/devtools', version: '0.1.0' }] }));
`, { mode: 0o755 });
  const invoke = args => new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cli, ...args], { cwd: root, env: { ...process.env, PATH: bin, NEXIA_CONFIG_HOME: config, INSTALL_LOG: log }, stdio: ['ignore', 'pipe', 'pipe'] });
    let output = '';
    child.stdout.on('data', chunk => { output += chunk; });
    child.stderr.on('data', chunk => { output += chunk; });
    child.once('error', reject);
    child.once('close', code => resolve({ code, output }));
  });
  let result = await invoke(['setup', '--devtools', '--dry-run']);
  assert.equal(result.code, 0, result.output);
  await assert.rejects(readFile(log), { code: 'ENOENT' });
  result = await invoke(['setup', '--devtools']);
  assert.equal(result.code, 0, result.output);
  const installed = JSON.parse(await readFile(log, 'utf8'));
  assert.deepEqual(installed.args, ['install', '--no-interaction', '--no-scripts', '--no-plugins', '--prefer-dist']);
  assert.equal(installed.cwd, await realpath(path.join(config, 'tools/devtools')));
  assert.equal(installed.home, path.join(config, 'tools/devtools/composer-home'));
  assert.deepEqual(JSON.parse(await readFile(path.join(installed.cwd, 'composer.json'), 'utf8')).config, { 'allow-plugins': false });
  const manifestPath = path.join(installed.cwd, 'composer.json');
  assert.equal(JSON.parse(await readFile(manifestPath, 'utf8')).require['nexia-cloud-os/devtools'], '^0.1');
  await writeFile(manifestPath, JSON.stringify({ require: { 'nexia/app-devtools': '*', 'example/keep': '^1' }, config: { 'allow-plugins': false } }));
  result = await invoke(['setup', '--devtools']);
  assert.equal(result.code, 0, result.output);
  assert.deepEqual(JSON.parse(await readFile(manifestPath, 'utf8')).require, { 'nexia-cloud-os/devtools': '^0.1', 'example/keep': '^1' });
  assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).args.slice(0, 4), ['update', 'nexia-cloud-os/devtools', '--with-all-dependencies', '--minimal-changes']);
  // A second setup updates the existing lock; it does not silently reinstall the old version.
  result = await invoke(['setup', '--devtools']);
  assert.equal(result.code, 0, result.output);
  assert.equal(JSON.parse(await readFile(log, 'utf8')).args[0], 'update');
  for (const oldName of ['nexia/devtools', 'nexia/app-devtools']) {
    await writeFile(manifestPath, JSON.stringify({ require: { [oldName]: '*', 'example/keep': '^1' }, config: { 'allow-plugins': false } }));
    await writeFile(path.join(installed.cwd, 'composer.lock'), JSON.stringify({ packages: [{ name: oldName, version: '0.1.0' }] }));
    result = await invoke(['setup', '--devtools']);
    assert.equal(result.code, 0, result.output);
    assert.deepEqual(JSON.parse(await readFile(manifestPath, 'utf8')).require, { 'nexia-cloud-os/devtools': '^0.1', 'example/keep': '^1' });
    assert.deepEqual(JSON.parse(await readFile(log, 'utf8')).args.slice(0, 5), ['update', 'nexia-cloud-os/devtools', oldName, '--with-all-dependencies', '--minimal-changes']);
  }
  // An explicit supported pin is preserved during name migration.
  await writeFile(manifestPath, JSON.stringify({ require: { 'nexia/devtools': '0.1.0' } }));
  result = await invoke(['setup', '--devtools']);
  assert.equal(result.code, 0, result.output);
  assert.equal(JSON.parse(await readFile(manifestPath, 'utf8')).require['nexia-cloud-os/devtools'], '0.1.0');
  await writeFile(path.join(installed.cwd, 'composer.lock'), '{broken');
  const lastInstall = await readFile(log, 'utf8');
  result = await invoke(['setup', '--devtools']);
  assert.equal(result.code, 1);
  assert.equal(await readFile(log, 'utf8'), lastInstall, 'Invalid locks must not be ignored');
  result = await invoke(['make:page', 'Summary', root, '--label-ko', '요약']);
  assert.equal(result.code, 1, 'A tool located inside the App is rejected even when its path is managed');
  const app = await mkdtemp(path.join(tmpdir(), 'nexia-managed-app-'));
  t.after(() => rm(app, { recursive: true, force: true }));
  result = await invoke(['make:page', 'Summary', app, '--label-ko', '요약']);
  assert.equal(result.code, 0, result.output);
});
